### ISSUE TITLE
我們有需要支援.net framework 4.6.2以下嗎?

### ISSUE THREAD

**Issue by flier268** [Cricle/Ao.Lang#6]
我注意到有些套件因為不支援[.net standard2.0](https://learn.microsoft.com/zh-tw/dotnet/standard/net-standard?tabs=net-standard-2-0)以下的框架，所以無法升級，我們還有需要支援低於.net framework 4.6.2的版本嗎?

然後.Net 5微軟已經不玩了，是否應該都更新為.NET 6?

**Comment by Cricle** [comment]
我看[这个](https://learn.microsoft.com/zh-cn/lifecycle/faq/dotnet-framework).NET461已经准备玩完了，感觉现在没必要支持.NET Framework了

但是很多公司都在.NET452所以在中国来说有点必要

**Comment by flier268** [comment]
不論是4.5.2還是4.6.2，都是.NET 4，其實升級並不太會遇到問題，除非系統還留在Windows XP，不然並沒有留在4.5.2的必要

**Comment by Cricle** [comment]
就怕会和我公司一样握住452不放
不过在失去LTS的时候丢弃那部分支持也是很有必要
跟着MS走起码问题不大

**Comment by flier268** [comment]
我是不太能理解抱著452不放是在幹嘛，還是趕快從[4.5.2遷移到4.6.2](https://learn.microsoft.com/zh-tw/dotnet/framework/migration-guide/runtime/4.5.2-4.6.2)吧！
我會發出pull request，裡面更新了nuget套件、Framework改為.net standard 2.0 & .net standard 2.1
也一並修掉Unit Test的那些錯誤
